# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Repos/alarm_clock/project/project_1/project_1.cache/wt [current_project]
set_property parent.project_path F:/Repos/alarm_clock/project/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo f:/Repos/alarm_clock/project/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  F:/Repos/alarm_clock/hdl/SpiCtrl.vhd
  F:/Repos/alarm_clock/hdl/common.vhd
  F:/Repos/alarm_clock/hdl/Delay.vhd
  F:/Repos/alarm_clock/hdl/OledExample.vhd
  F:/Repos/alarm_clock/hdl/OledInit.vhd
  F:/Repos/alarm_clock/hdl/int2ascii.vhd
  F:/Repos/alarm_clock/hdl/trigger_gen.vhd
  F:/Repos/alarm_clock/hdl/PmodOLEDCtrl.vhd
  F:/Repos/alarm_clock/hdl/controller.vhd
  F:/Repos/alarm_clock/hdl/display.vhd
  F:/Repos/alarm_clock/hdl/clock_div.vhd
  F:/Repos/alarm_clock/hdl/alarm_clock.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Repos/alarm_clock/xdc/ZYBO_Master.xdc
set_property used_in_implementation false [get_files F:/Repos/alarm_clock/xdc/ZYBO_Master.xdc]


synth_design -top alarm_clock -part xc7z010clg400-1


write_checkpoint -force -noxdef alarm_clock.dcp

catch { report_utilization -file alarm_clock_utilization_synth.rpt -pb alarm_clock_utilization_synth.pb }
